routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\HomeController;
// use App\Http\Controllers\ProductController;
use App\Http\Controllers\UsermanagementController;
use App\Http\Controllers\DepartementuserController;


// MENU MASTER
use App\Http\Controllers\Master\BarangController;
use App\Http\Controllers\Master\CabangController;
use App\Http\Controllers\Master\SupplierController;
use App\Http\Controllers\Master\FactoryController;
use App\Http\Controllers\Master\DepartementController;
use App\Http\Controllers\Master\CorporateController;
use App\Http\Controllers\Master\DokterController;
use App\Http\Controllers\Master\MarketingActivityController;
use App\Http\Controllers\Master\BarangBaruController;
use App\Http\Controllers\Master\MinMaxController;
use App\Http\Controllers\Master\NonAktifkanPOController;
use App\Http\Controllers\Master\KategoriController;
use App\Http\Controllers\Master\KaryawanController;
use App\Http\Controllers\Master\MenuController;
use App\Http\Controllers\Master\UserController;
use App\Http\Controllers\Master\AreaController;
use App\Http\Controllers\Master\RoleController;
use App\Http\Controllers\Master\SatuanController;
use App\Http\Controllers\Master\StokBarangController;


// MENU LAPORAN
use App\Http\Controllers\Laporan\LaporanPenjualanController;
use App\Http\Controllers\Laporan\LaporanPembelianController;
use App\Http\Controllers\Laporan\SelisihPersediaanController;
use App\Http\Controllers\Laporan\SelisihExpiredController;
use App\Http\Controllers\Laporan\LaporanOmsetController;
use App\Http\Controllers\Laporan\LaporanCNDNController;
use App\Http\Controllers\Laporan\LaporanHargaBarangController;
use App\Http\Controllers\Laporan\LaporanPenjualanDalamPeriodeController;
use App\Http\Controllers\Laporan\LaporanOmsetPenjualanBarangController;
use App\Http\Controllers\Laporan\LaporanPenjualanByTipeTransaksiController;
use App\Http\Controllers\Laporan\LaporanPenjualanByJenisCustomerController;
use App\Http\Controllers\Laporan\LaporanPenjualanBarangByNamaDokterController;
use App\Http\Controllers\Laporan\LaporanPenjualanBarangByCustomerController;
use App\Http\Controllers\Laporan\LaporanPembelianBarangQTYController;
use App\Http\Controllers\Laporan\LaporanPembelianBarangController;
use App\Http\Controllers\Laporan\LaporanBuktiPurchaseOrderController;
use App\Http\Controllers\Laporan\LaporanBuktiPurchaseOrderLangsungController;
use App\Http\Controllers\Laporan\ResiPOPembelianController;
use App\Http\Controllers\Laporan\LaporanInputBarangExpiredController;
use App\Http\Controllers\Laporan\LaporanReturController;
use App\Http\Controllers\Laporan\LaporanDeliveryController;
use App\Http\Controllers\Laporan\LaporanTransferAntarOutletSummaryController;
use App\Http\Controllers\Laporan\LaporanKartuHutangController;
use App\Http\Controllers\Laporan\LaporanKartuPiutangController;
use App\Http\Controllers\Laporan\LaporanKartuPiutangDepoController;
use App\Http\Controllers\Laporan\LaporanOSSController;
use App\Http\Controllers\Laporan\LaporanStockSaatIniController;
use App\Http\Controllers\Laporan\LaporanNotasiBarangController;
use App\Http\Controllers\Laporan\LaporanPerhitunganHPPPerAbjadController;
use App\Http\Controllers\Laporan\TabelInfoNarkotikaController;
use App\Http\Controllers\Laporan\LaporanNarkotikaController;
use App\Http\Controllers\Laporan\LaporanNarkotikadanPsikotoprikaController;
use App\Http\Controllers\Laporan\LaporanNilaiPenjualanPerJamController;
use App\Http\Controllers\Laporan\LaporanParetoPenjualanController;
use App\Http\Controllers\Laporan\LaporanPenjualanBarangTertentuController;
use App\Http\Controllers\Laporan\LaporanQTYJualPerJamController;
use App\Http\Controllers\Laporan\LaporanStockProdukSummaryController;
use App\Http\Controllers\Laporan\LaporanStockKosongController;
use App\Http\Controllers\Laporan\LaporanNilaiInventoryByPeriodeController;
use App\Http\Controllers\Laporan\RekapController;
use App\Http\Controllers\Laporan\DetailController;
use App\Http\Controllers\Laporan\LaporanAntrianResepController;
use App\Http\Controllers\Laporan\LaporanKonstribusiDepartemenController;

// MENU TRANSAKSI

// MENU APOTEK

// MENU SETUP

// MENU MAINTENANCE

// MENU AUDIT

// MENU MANAGER

// MENU REMIND PASIEN

// MENU TRANSFER DATA

// MENU SERVICE LEVEL

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LoginController::class, 'index']);
Route::resource('home', HomeController::class);
Route::get('login', [LoginController::class, 'index'])->name('login');
Route::get('logout', [LoginController::class, 'logout']);

Route::post('auth/login', [LoginController::class, 'login'])->name('auth.login');

Route::group(['middleware' => 'cekauth'], function () {
	// MENU DISPLAY
	Route::resource('usermanagement', UsermanagementController::class);
	// Route::resource('product', ProductController::class);
	Route::resource('departementuser', DepartementuserController::class);

	// MENU MASTER
	Route::resource('barang', BarangController::class);
	Route::resource('cabang', CabangController::class);
	Route::resource('supplier', SupplierController::class);
	Route::resource('factory', FactoryController::class);
	Route::resource('departement', DepartementController::class);
	Route::resource('corporate', CorporateController::class);
	Route::resource('dokter', DokterController::class);
	Route::resource('marketing_activity', MarketingActivityController::class);
	Route::resource('usulan_barang_baru', BarangBaruController::class);
	Route::resource('min_max', MinMaxController::class);
	Route::resource('non_aktifkan_po', NonAktifkanPOController::class);
	Route::resource('kategori', KategoriController::class);
	Route::resource('karyawan', KaryawanController::class);
	Route::resource('menu', MenuController::class);
	Route::resource('user', UserController::class);
	Route::resource('area', AreaController::class);
	Route::resource('role', RoleController::class);
	Route::resource('satuan', SatuanController::class);
	Route::resource('stokbarang', StokBarangController::class);


	// MENU LAPORAN

	// Laporan Penjualan
	Route::get('laporan_penjualan/print', [LaporanPenjualanController::class,'print']);
	Route::resource('laporan_penjualan', LaporanPenjualanController::class);
	//

	// Laporan Penjualan dalam Periode
	Route::get('laporan_penjualan_dalam_periode/print', [LaporanPenjualanDalamPeriodeController::class, 'print']);
	Route::resource('laporan_penjualan_dalam_periode', LaporanPenjualanDalamPeriodeController::class);
	//

	// Laporan Omzet Penjualan Barang
	Route::get('laporan_omset_penjualan_barang/print', [LaporanOmsetPenjualanBarangController::class, 'print']);
	Route::resource('laporan_omset_penjualan_barang', LaporanOmsetPenjualanBarangController::class);

	// Laporan Penjualan By Type Transaksi
	Route::get('laporan_penjualan_transaksi/print_resep', [LaporanPenjualanByTipeTransaksiController::class,'print_resep']);
	Route::get('laporan_penjualan_transaksi/print_swalayan', [LaporanPenjualanByTipeTransaksiController::class,'print_swalayan']);
	Route::resource('laporan_penjualan_transaksi', LaporanPenjualanByTipeTransaksiController::class);

	// Laporan Pembelian Barang QTY
	Route::get('laporan_pembelian_barang_qty/print', [LaporanPembelianBarangQTYController::class, 'print']);
	Route::resource('laporan_pembelian_barang_qty', LaporanPembelianBarangQTYController::class);

	Route::get('laporan_penjualan_by_nama_dokter/per_dokter', [LaporanPenjualanBarangByNamaDokterController::class, 'per_dokter']);
	Route::get('laporan_penjualan_by_nama_dokter/all_dokter', [LaporanPenjualanBarangByNamaDokterController::class, 'all_dokter']);
	Route::get('laporan_penjualan_by_nama_dokter/rekap_omset', [LaporanPenjualanBarangByNamaDokterController::class, 'rekap_omset']);
	Route::get('laporan_penjualan_by_nama_dokter/rekap_sc', [LaporanPenjualanBarangByNamaDokterController::class, 'rekap_sc']);
	Route::resource('laporan_penjualan_by_nama_dokter', LaporanPenjualanBarangByNamaDokterController::class);

	Route::resource('laporan_pembelian', LaporanPembelianController::class);
	Route::resource('selisih_persediaan', SelisihPersediaanController::class);
	Route::resource('selisih_expired', SelisihExpiredController::class);
	Route::resource('laporan_omset', LaporanOmsetController::class);
	Route::resource('laporan_cn_dn', LaporanCNDNController::class);
	Route::resource('laporan_harga_barang', LaporanHargaBarangController::class);

	Route::resource('laporan_penjualan_customer', LaporanPenjualanByJenisCustomerController::class);
	Route::resource('laporan_penjualan_by_customer', LaporanPenjualanBarangByCustomerController::class);
	Route::resource('laporan_pembelian_barang', LaporanPembelianBarangController::class);
	Route::resource('laporan_purchase_order', LaporanBuktiPurchaseOrderController::class);
	Route::resource('laporan_bukti_purchase', LaporanBuktiPurchaseOrderLangsungController::class);
	Route::resource('resi_po_pembelian', ResiPOPembelianController::class);
	Route::resource('laporan_input_barang_expired', LaporanInputBarangExpiredController::class);
	Route::resource('laporan_retur', LaporanReturController::class);
	Route::resource('laporan_delivery', LaporanDeliveryController::class);
	Route::resource('laporan_transfer_outlet', LaporanTransferAntarOutletSummaryController::class);
	Route::resource('laporan_kartu_hutang', LaporanKartuHutangController::class);
	Route::resource('laporan_kartu_piutang', LaporanKartuPiutangController::class);
	Route::resource('laporan_kartu_piutangDepo', LaporanKartuPiutangDepoController::class);

app/Http/Controllers/Master/AreaController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Session;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;

class AreaController extends Controller
{
    public function index()
    {
        // $token = Session::get('access_token');
        // exit;
        $client = new Client(); 
        $url = "https://api.app-sandbox.xyz/api/area";
        $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmFwcC1zYW5kYm94Lnh5elwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY2Mzk0MTkwOSwiZXhwIjoxNjY2NTMzOTA5LCJuYmYiOjE2NjM5NDE5MDksImp0aSI6InBpN0U1eUl3a05pY1E4cHciLCJzdWIiOjIzLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.MsaX_zqYLjPvKmER9LPMqAQgAq-lc84IGjvI2V9cePI";

        $response = $client->get($url, [
            'headers'=> [
                'Authorization' => 'Bearer '.$token
            ]
        ]);

        $body = $response->getBody()->getContents();

        $records = json_decode($body, true);

        return view('master.area.list', compact('records', 'token'));
    }

    public function create()
    {
        return view('master.area.form');
    }

    public function store(Request $request)
    {
        $client = new Client(); 
        $url = "https://api.app-sandbox.xyz/api/area/create";
        $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmFwcC1zYW5kYm94Lnh5elwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY2MzkzNDgwMywiZXhwIjoxNjY2NTI2ODAzLCJuYmYiOjE2NjM5MzQ4MDMsImp0aSI6IjE4TUZsSFplVkhNd0d0dG4iLCJzdWIiOjIzLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQ8IMlermvzWpNOBhqR1iNSYxa3CILFiEJQGy1gG5GU";

        try {
            $response = $client->post($url, [
                'headers'=> [
                    'Authorization' => 'Bearer '.$token
                ],
                'form_params' => [
                    'nmArea' => $request->nmArea
                ]
            ]);

            $msg = json_decode($response->getBody()->getContents());

            if ($msg->status == 1){
                return redirect()->route('area.index')->with('alert-success', 'Data Berhasil Disimpan.');
            }

        } catch (RequestException $e) {
            if ($e->hasResponse()){
                if ($e->getResponse()->getStatusCode() == '400') {
                    return redirect()->route('area.index')->with('alert-error', 'Data Gagal Disimpan.');
                }
            }
        }
    }

    public function edit($id)
    {
        $client = new Client(); 
        $url = "https://api.app-sandbox.xyz/api/area/get/".$id;
        $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmFwcC1zYW5kYm94Lnh5elwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY2MzkzNDgwMywiZXhwIjoxNjY2NTI2ODAzLCJuYmYiOjE2NjM5MzQ4MDMsImp0aSI6IjE4TUZsSFplVkhNd0d0dG4iLCJzdWIiOjIzLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQ8IMlermvzWpNOBhqR1iNSYxa3CILFiEJQGy1gG5GU";

        $response = $client->get($url, [
            'headers'=> [
                'Authorization' => 'Bearer '.$token
            ]
        ]);

        $body = $response->getBody()->getContents();

        $arrData = json_decode($body, true);

        $record = [];
        foreach($arrData['data'] as $row){
            $record = ([
                'id_area' => $row['id_area'],
                'nm_area' => $row['nm_area']
            ]);
        }

        return view('master.area.form', compact('record'));
    }

    public function update(Request $request, $id)
    {
        $client = new Client(); 
        $url = "https://api.app-sandbox.xyz/api/area/update/".$id;
        $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmFwcC1zYW5kYm94Lnh5elwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY2MzkzNDgwMywiZXhwIjoxNjY2NTI2ODAzLCJuYmYiOjE2NjM5MzQ4MDMsImp0aSI6IjE4TUZsSFplVkhNd0d0dG4iLCJzdWIiOjIzLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQ8IMlermvzWpNOBhqR1iNSYxa3CILFiEJQGy1gG5GU";

        try {
            $response = $client->put($url, [
                'headers'=> [
                    'Authorization' => 'Bearer '.$token
                ],
                'form_params' => [
                    'nmArea' => $request->nmArea
                ]
            ]);

            $msg = json_decode($response->getBody()->getContents());

            if ($msg->status == 1){
                return redirect()->route('area.index')->with('alert-success', 'Data Berhasil Disimpan.');
            }

        } catch (RequestException $e) {
            if ($e->hasResponse()){
                if ($e->getResponse()->getStatusCode() == '400') {
                    return redirect()->route('area.index')->with('alert-error', 'Data Gagal Disimpan.');
                }
            }
        }
    }

    public function destroy($id): JsonResponse
    {
        $client = new Client(); 
        $url = "https://api.app-sandbox.xyz/api/area/delete/".$id;
        $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYXBpLmFwcC1zYW5kYm94Lnh5elwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTY2MzkzNDgwMywiZXhwIjoxNjY2NTI2ODAzLCJuYmYiOjE2NjM5MzQ4MDMsImp0aSI6IjE4TUZsSFplVkhNd0d0dG4iLCJzdWIiOjIzLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yQ8IMlermvzWpNOBhqR1iNSYxa3CILFiEJQGy1gG5GU";

        $response = $client->delete($url, [
            'headers'=> [
                'Authorization' => 'Bearer '.$token
            ]
        ]);

        $msg = json_decode($response->getBody()->getContents());

        if ($msg->status == 1){
            $res['status'] = 'success';
        }

        return response()->json($res);
    }
}

app/Http/Controllers/Master/BarangBaruController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

class BarangBaruController extends Controller
{
    public function index()
    {
        return view('master.usulan_barang_baru.list');
    }

    public function create()
    {
        return view('master.usulan_barang_baru.form');
    }

    public function store()
    {
    }

    public function edit($id)
    {
        $data['record'] = $id;
        return view('master.usulan_barang_baru.form', $data);
    }

    public function update()
    {
    }

    public function destroy($id): JsonResponse
    {
    }
}

app/Http/Controllers/Master/BarangController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

class BarangController extends Controller
{
    public function index()
    {
        return view('master.barang.list');
    }

    public function create()
    {
        return view('master.barang.form');
    }

    public function store()
    {
    }

    public function edit($id)
    {
        $data['record'] = $id;
        return view('master.barang.form', $data);
    }

    public function update()
    {
    }

    public function destroy($id): JsonResponse
    {
    }
}

app/Http/Controllers/Master/CabangController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;

class CabangController extends Controller
{
    public function index()
    {
        return view('master.cabang.list');
    }

    public function create()
    {
        return view('master.cabang.form');
    }

    public function store()
    {
    }

    public function edit($id)
    {
        $data['record'] = $id;
        return view('master.cabang.form', $data);
    }

    public function update()
    {
    }

    public function destroy($id): JsonResponse
    {
    }
}

resources/views/master/area/form.blade.php
@extends('layouts.theme')

@section('content')

<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;">Page Options</a></li>
        <li class="active">Page with Top Menu</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Page with Top Menu <small>header small text goes here...</small></h1>
    <!-- end page-header -->
    
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">Panel Title here</h4>
                </div>
                <div class="panel-body">
                    <!-- Content Disini -->
                    <form class="form-horizontal" 
                        action="{{ isset($record) ? route('area.update', $record['id_area']) : route('area.store') }}" method="POST" novalidate>

                        @isset($record)
                            @method('PUT')
                        @endisset

                        @csrf
                        <h3 class="card-title">Tambah Data Area</h3>
                        <hr>
                        <!-- ROW 2 -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Nama Area</label>
                                    <input type="text" name="nmArea" id="nmArea" 
                                        class="form-control" placeholder="Nama Area" 
                                        value="{{ $record['nm_area'] ?? old('nm_area') }}" autofocus>
                                </div>
                            </div>
                        </div>
                        <!-- END ROW 2-->

                        <div class="form-actions">
                            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save</button>
                            <button type="button" class="btn btn-danger"><i class="fa fa-times"></i> Cancel</button>
                        </div>
                    </form>
                    <!-- End -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('javascript')
<script>
</script>
@endsection

resources/views/master/area/list.blade.php
@extends('layouts.theme')

@section('content')

<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="javascript:;">Home</a></li>
        <li><a href="javascript:;">Page Options</a></li>
        <li class="active">Page with Top Menu</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Page with Top Menu <small>header small text goes here...</small></h1>
    <!-- end page-header -->
    
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">Master Area</h4>
                </div>
                <div class="panel-body">
                    <!-- Content Disini -->
                    <a href="{{ route('area.create') }}" class="btn btn-info waves-effect waves-light" type="button">
                        <span class="btn-label m-r-5"><i class="fas fa-plus"></i></span> Tambah
                    </a>

                    <div class="table-responsive m-t-20">
                        <table class="table table-bordered table-striped no-paddding dataTable">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>ID Area</th>
                                    <th>Nama Area</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($records['data'] as $key => $row)
                                <tr>
                                    <td>{{ $key + 1 }}.</td>
                                    <td>{{ $row['id_area'] }}</td>
                                    <td>{{ $row['nm_area'] }}</td>
                                    <td>
                                        <a href="{{ route('area.edit', $row['id_area']) }}" type="button" class="btn waves-effect btn-info btn-sm">
                                            <i class="ti-pencil-alt"></i> Ubah
                                        </a>
                                        <button type="button" data-id="{{ $row['id_area'] }}" class="btn waves-effect btn-danger btn-sm hapus">
                                            <i class="ti-trash"></i> Hapus
                                        </button>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- End -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('javascript')
<script>
</script>
@endsection